### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by alamers** [caseymrm/drivesink#3]
Hi,

I got the following traceback when trying your script:

Traceback (most recent call last):
  File "./drivesink.py", line 272, in <module>
    main()
  File "./drivesink.py", line 261, in main
    drivesink.upload(args.source, args.destination)
  File "./drivesink.py", line 109, in upload
    self.get_root(), destination, create_missing=True)
  File "./drivesink.py", line 151, in get_root
    nodes = self.request_metadata("%snodes?filters=isRoot:True")
  File "./drivesink.py", line 207, in request_metadata
    path % self._config()["metadataUrl"], **args)
  File "./drivesink.py", line 238, in _request
    req.raise_for_status()
  File "/Users/arjanl/Documents/drivesink/drivesink-master/drivesinkenv/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request

It seems that I can fix that error by changing line 151:
nodes = self.request_metadata("%snodes?filters=isRoot:True")

should be
nodes = self.request_metadata("%snodes?filters=isRoot:true")

(lower case 't' in true).

**Comment by mike-lawrence** [comment]
Ditto on encountering this error, and that the suggested fix works. Thanks alamers!

**Comment by caseymrm** [comment]
Fixed by 5c8713aeb6f8e8e8c014448a8880874dace361d2, thanks!
