### ISSUE TITLE
Token issue stopped working - HTTP 429

### ISSUE THREAD

**Issue by mas90** [caseymrm/drivesink#30]
At https://drivesink.appspot.com/config I get:

```
Internal Server Error
The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/apps/s~drivesink/1.381807125840328671/main.py", line 99, in handle_exception
    super(SinkHandler, self).handle_exception(exception, debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~drivesink/1.381807125840328671/main.py", line 163, in get
    token.update(self._endpoints())
  File "/base/data/home/apps/s~drivesink/1.381807125840328671/main.py", line 84, in _endpoints
    "https://drive.amazonaws.com/drive/v1/account/endpoint")
  File "/base/data/home/apps/s~drivesink/1.381807125840328671/main.py", line 61, in _fetch
    return self._fetch(url, data, refresh=False)
  File "/base/data/home/apps/s~drivesink/1.381807125840328671/main.py", line 57, in _fetch
    return urllib2.urlopen(req).read()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/urllib2.py", line 158, in urlopen
    return opener.open(url, data, timeout)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/urllib2.py", line 439, in open
    response = meth(req, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/urllib2.py", line 552, in http_response
    'http', request, response, code, msg, hdrs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/urllib2.py", line 477, in error
    return self._call_chain(*args)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/urllib2.py", line 411, in _call_chain
    result = func(*args)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/urllib2.py", line 560, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 429: Unknown
```

And the old token I got before that started happening no longer works either; Amazon returns HTTP 401 and "Token has expired".

**Comment by caseymrm** [comment]
Hmm, they may have finally invalidated my credentials. I haven't logged in forever, let me get in there and poke around.

**Comment by E6L** [comment]
@caseymrm  ?

**Comment by caseymrm** [comment]
Sorry, I have been unable to get this working again so far. If anybody can successfully get a new set of credentials I (or they) can get a site up again.
